### ISSUE TITLE
semver increment force pushes, skipping downstream workflow

### ISSUE THREAD

**Issue by roc** [UKHomeOffice/sas-github-workflows#17]
https://github.com/UKHomeOffice/sas-github-workflows/blob/e83cc566b21ca8ead8718bf93a6b6e7ef14ec300/.github/workflows/semver-check-increment-npm.yml#L62

Additionally this is a "bot" change, not a user authored commit, but it's force pushed as if by the same author, obscuring the intention to push a new version of the package.

Could it be instead signed something like:

```bash
git config user.name 'github-actions[bot]'
git config user.email 'github-actions[bot]@users.noreply.github.com'
git commit -m "Automatically incrementing to ${{ env.NEW_VERSION }}"
git push --set-upstream origin ${{ github.head_ref }}
```

Either that or setting a co-authoring step e.g.

```bash
git commit --amend -m "`git log -n 1 --pretty=format:%s` (Automatically incrementing to ${{ env.NEW_VERSION }})"$'\n\n'"co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
```

which would produce something along the lines of 

```
commit e9d11d39bcf15c8dd44rf9b0b8902ef6f19d1612 (source -> target)
Author: Ralph Cowling <ralph@ralph-cowling.com>
Date:   Thu May 11 15:56:51 2023 +0200

    Original commit message (Automatically incrementing to v11.1.0)

    co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
```

**Comment by nickmcmahon01** [comment]
This is a good point and its current state wasn't a deliberate decision, let's use github-actions as the author and the $GITHUB_ACTOR as the co-author. One benefit of doing it this way round is we can filter these out by author when automating release notes.

**Comment by nickmcmahon01** [comment]
https://ardislu.dev/proper-git-for-github-actions

**Comment by nickmcmahon01** [comment]
https://github.com/UKHomeOffice/asl-constants-gha-test/pull/35 👌
